C018:何人前作れる？
shimizu0623/paiza_practice pull request #102
Opened 2022-09-10 08:25 UTC by shimizu0623

お疲れ様です！
苦し紛れに解いてみましたが、全問正解できませんでした😢
お手数ですが、お手すきの際にご確認よろしくお願い致します🙇🙇

![image](https://user-images.githubusercontent.com/89590207/189475309-a8f5b6dd-eb60-4cd3-813c-f36f525b6042.png)

2022-09-19 15:22 UTC, yuki-omoto requested changes
@shimizu0623 
ロジックは完璧です！！
for文の範囲でミスがありそうでしたので、コメントさせていただきました 🙇

2022-09-19 15:22 UTC, yuki-omoto commented on rank_C/C018.js
> +  for (let i = itemValue; i < itemValue * 2; i++){
@shimizu0623 
ここの範囲が間違っていました。。 🙇 
スタートとエンドどちらも違いそうです 🙇 
それぞれの変数がなんの意味なのかを落ち着いて整理するとわかるかと思います！ (ここ直すだけで大丈夫です！)

2022-09-19 15:22 UTC, yuki-omoto commented on rank_C/C018.js
> +        if (Object.keys(items)[i] === Object.keys(recipes)[j]){
@shimizu0623 
Object.keysやObject.valuesが何度か出てきますが、ループの中で使う時には外で定義できないか？というのを考えるようにしましょう 🙇
この例だと、ループによって変わるのは i だけなので、Object.keys(items)までは外側に出せそうですね 🙇

2022-09-29 07:35 UTC, shimizu0623 commented on rank_C/C018.js
> +  for (let i = itemValue; i < itemValue * 2; i++){
範囲、全然違っておりました🙇💦
修正致します！

2022-09-29 07:36 UTC, shimizu0623 commented on rank_C/C018.js
> +        if (Object.keys(items)[i] === Object.keys(recipes)[j]){
ループの度、配列を作ってしまうやつですね🙇💦
こちらも修正致します！

2022-09-29 07:39 UTC, shimizu0623 commented
お疲れ様です！
コメントありがとうございました🙇💦
修正完了しましたので、ご確認よろしくお願い致します🙇🙇

2022-09-30 16:30 UTC, yuki-omoto approved these changes
@shimizu0623 
完璧です！ 🙇 
お疲れさまでした 👏

2022-09-30 16:30 UTC, merged