C094:国民の税金
shimizu0623/paiza_practice pull request #111
Opened 2022-09-13 02:26 UTC by shimizu0623

お疲れ様です！
問題の意味が良く分からず、答えがどうしても75000分足りないと出てしまうので、一度上げさせていただきました🙇
どこかに75000足すのでしょうか？🤔
お手数ですが、ヒントいただけますと幸いです🙇
ご確認よろしくお願い致します🙇

![image](https://user-images.githubusercontent.com/89590207/189793266-6a27c9ed-6cc9-46d4-a7cf-7141a4eac1a4.png)

2022-09-19 11:23 UTC, yuki-omoto requested changes
@shimizu0623 
遅くなって申し訳ありません 🙇 
区間の税金を全部計算しておくというやり方、すごく賢いですね！
僕はそれは思いつかなくて、違うやり方でやりました 🙇 

いい感じだと思いますが、凡ミス(？)みたいなところがありましたので、それが原因っぽいです！ 🙇

2022-09-19 11:23 UTC, yuki-omoto commented on rank_C/C094.js
> +    const tax20 = (1500000 - 750000) * 0.1;
@shimizu0623 
ここは20%なので、0.2かと思います 🙇

2022-09-28 14:47 UTC, shimizu0623 commented on rank_C/C094.js
> +    const tax20 = (1500000 - 750000) * 0.1;
あ、、💦なぜ気付けなかったのでしょう🙇💦笑
教えていただき、ありがとうございます！笑

2022-09-28 14:48 UTC, shimizu0623 commented
解答修正し、全問正解できました！笑
ご確認よろしくお願い致します！🙇🙇

2022-09-30 16:53 UTC, yuki-omoto approved these changes
@shimizu0623 
修正確認しました！！

2022-09-30 16:53 UTC, merged