C031:時差を求めたい
shimizu0623/paiza_practice pull request #114
Opened 2022-09-13 04:51 UTC by shimizu0623

お疲れ様です！
テストでは正解になったのですが、提出すると不正解になってしまった問題です😢
解き方の方向性も不安でしたので、ヒントいただけますと幸いです🙇
お手数ですが、ご確認よろしくお願い致します🙇🙇

![image](https://user-images.githubusercontent.com/89590207/189811504-010c58e6-a47e-40cc-aa29-8629e2886719.png)

2022-09-30 17:09 UTC, yuki-omoto requested changes
@shimizu0623 

これで全部解決するかわかりませんが、取り急ぎ見つけたやつを報告いたします 🙇 
自由入力のところでテストしたところ↓のような入力だとbbbが25時みたいになっていました 🙇 

```
4
bbb 14
ccc 4
london 0
aaa -12
aaa 23:39
```

2022-10-01 09:36 UTC, shimizu0623 commented
ご報告ありがとうございます！！🙇🙇
修正したところ、×が７個→３個に少し減りましたが、時間切れだったため再度上げさせていただきました🙇🙇
恐れ入りますが、後程ご確認よろしくお願い致します🙇💦

2022-10-01 16:06 UTC, yuki-omoto commented
@shimizu0623 

取り急ぎ僕の回答です 🙇 

```
process.stdin.resume();
process.stdin.setEncoding('utf8');
// 自分の得意な言語で
// Let's チャレンジ！！
var lines = [];
var reader = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});
reader.on('line', (line) => {
  lines.push(line);
});
reader.on('close', () => {
    const posts = lines.slice(1, lines.length - 1).map(p => p.split(' '))
    const [place, now] = lines[lines.length - 1].split(' ')
    const [hour, min] = now.split(':')
    const myTimeDiff = posts.find(p => p[0] === place)[1]
    const utcNow = parseInt(hour) - myTimeDiff
    const DAY = 24
    const timezonedPosts = posts.map(([p, time]) => {
        let timezoneAdjusted = utcNow + parseInt(time)
        if (timezoneAdjusted >= DAY) {
            timezoneAdjusted -= DAY
        } else if (timezoneAdjusted < 0) {
            timezoneAdjusted += DAY
        }
        return `${('0' + timezoneAdjusted.toString()).slice(-2)}:${min}`
    })
    console.log(timezonedPosts.join('\n'));
});
```

2022-10-01 16:31 UTC, yuki-omoto commented
@shimizu0623 

清水さんのコードと僕のコードのロジックは同じですし、何回見てもどこが間違っているのかわかっていません。。 🙇

2022-10-02 03:27 UTC, shimizu0623 commented
コメントありがとうございます！！
私も再度考えてみたのですが、全問正解にはなりませんでした、、😢ので、
大本さんのコードを参考にさせていただきます🙇
お手すきの際に、ご確認よろしくお願い致します🙇

2022-10-02 04:45 UTC, yuki-omoto approved these changes
この問題はかなり謎でした 🙇
ただ、ロジックとか見てもあっていそうなので、事実上清水さんのやつでOKだったと思います！

2022-10-02 04:45 UTC, merged