C118:ダイヤル錠
shimizu0623/paiza_practice pull request #116
Opened 2022-10-01 01:56 UTC by shimizu0623

お疲れ様です！
こちら新しい問題が追加されていたので、解いてみたのですが、全問正解はできませんでした😢
お手数ですが、こちらもご確認よろしくお願い致します🙇🙇

![image](https://user-images.githubusercontent.com/89590207/193378559-406ed752-3ce7-4b55-b601-633db2e050b3.png)

2022-10-01 15:48 UTC, yuki-omoto commented
@shimizu0623 

取り急ぎ、一旦僕のコードですが、これでいけました。。！
僕も3回くらい間違えました 🙇 
0を跨ぐパターンも考慮するのがちょっと複雑そうです 🙇 

```
process.stdin.resume();
process.stdin.setEncoding('utf8');
// 自分の得意な言語で
// Let's チャレンジ！！
var lines = [];
var reader = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});
reader.on('line', (line) => {
  lines.push(line);
});
reader.on('close', () => {
    let [max, , duration] = lines[0].split(' ').map(n => parseInt(n))
    const operations = lines.slice(1).map(n => parseInt(n))
    let current = 0
    for (let i = 0; i < operations.length; i++) {
        const closedWay = Math.abs(current - operations[i])
        const roundWay = Math.abs(Math.min(current, operations[i]) + max - Math.max(current, operations[i]))
        const value = Math.min(closedWay, roundWay)
        duration -= value
        if (duration <= 0) {
            console.log('No')
            return
        }
        current = operations[i]
    }
    console.log('Yes');
});
```

これから清水さんのやつみます 🙇

2022-10-01 15:59 UTC, yuki-omoto requested changes
@shimizu0623 
基本いい感じだと思います！ 🙇 

初回の反対周りパターンを修正するだけでいけそうな気がします 🙇 
間違っていたらごめんなさい🙇 🙇  
コメントつけて修正してみました 🙇 

```
process.stdin.resume();
process.stdin.setEncoding('utf8');
var lines = [];
var reader = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});
reader.on('line', (line) => {
  lines.push(line);
});
reader.on('close', () => {
  const [number, , broken] = lines[0].split(' ').map(n => parseInt(n));
  let answer = 'No';
  let firstNumber = parseInt(lines[1]);
  let count = Math.min(firstNumber, number - firstNumber) // 初回に反対周りの方が短い時を考慮
  const halfPoint = Math.floor(number / 2);

  for (let i = 2; i < lines.length; i++){
    const calc = Math.abs(parseInt(lines[i]) - parseInt(lines[i - 1]));

    if (halfPoint < calc){
        const max = Math.max(parseInt(lines[i]), parseInt(lines[i - 1]));
        const min = Math.min(parseInt(lines[i]), parseInt(lines[i - 1]));
        const counterCalc = number - max + min;
        count += counterCalc;
    } else {
        count += calc;
    }
  }

  if (count < broken){
    answer = 'Yes';
  }

  console.log(answer);
});
```

2022-10-02 01:07 UTC, shimizu0623 commented
見ていただいて、ありがとうございます！
初回の反対周りをすっかり失念しておりました🙇💦
全問正解になりましたので、お手すきの際に、ご確認よろしくお願い致します🙇

2022-10-02 04:49 UTC, yuki-omoto approved these changes
こちらも完璧です！お疲れさまでした🙇

2022-10-02 04:49 UTC, merged