C068:秘密の手紙の解答
shimizu0623/paiza_practice pull request #60
Opened 2022-08-18 02:21 UTC by shimizu0623

お疲れ様です！
10ケース中、5問×になってしまった問題です😢
お手数をおかけしますが、後程ご確認よろしくお願い致します🙇

![image](https://user-images.githubusercontent.com/89590207/185278533-332f784c-3b1f-46e8-b2ad-08c1854cc418.png)

2022-09-24 07:34 UTC, yuki-omoto requested changes
@shimizu0623 

数字に変換と言ったんですが、一応charCodeAtなどを使うという意味でした 🙇 申し訳ありません 🙇 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt

ただ、これをやってもやらなくてもロジックは変わらないと思うので、あまり効果はないかもです 🙇 
一点おかしそうな箇所がありましたので、コメントさせていただきましたので、それが原因かもです 🙇

2022-09-24 07:34 UTC, yuki-omoto commented on rank_C/C068.js
> +        if (order[i] === j + 1){
@shimizu0623 

```
4
AZPG
```

という入力で試すと、DLKになって最初の文字が消えてしまいました 🙇 
WDLKになるのが正解ですが、ここが解決するといけるかもです 🙇🙇

2022-10-01 10:04 UTC, shimizu0623 commented
お疲れ様です！コメントありがとうございます！🙇

 > 数字に変換と言ったんですが、一応charCodeAtなどを使うという意味でした 🙇
すみません、charCodeAt知りませんでした！こうやって変換することができるのですね👀勉強になりました！🙇🙇

いただいたコメントの部分を修正したところ、全問正解できました😊
念の為、こちらもご確認よろしくお願い致します🙇🙇

2022-10-01 10:06 UTC, shimizu0623 commented on rank_C/C068.js
> +        if (order[i] === j + 1){
奇数と偶数のところで、order[i] が 0の時の処理をそれぞれ追加したところ、全問正解できました😊
修正して上げさせていただきます🙇

2022-10-01 15:03 UTC, yuki-omoto approved these changes
@shimizu0623 
全問正解できてよかったです！いい感じです 🙇

2022-10-01 15:03 UTC, merged