C111:ハッシュ関数
shimizu0623/paiza_practice pull request #77
Opened 2022-08-30 01:48 UTC by shimizu0623

お疲れ様です！
例題２がどうしても答えが合わず、ギブアップした問題です😭
お手数ですが、お時間のある際にヒントをいただけますと幸いです🙇🙇

![image](https://user-images.githubusercontent.com/89590207/187329647-e6a3cecf-3d2d-401f-a571-80ec00164913.png)

2022-09-24 07:50 UTC, yuki-omoto requested changes
@shimizu0623 
エラーになりそうなケースを見つけましたので、報告いたします 🙇

2022-09-24 07:50 UTC, yuki-omoto commented on rank_C/C111.js
> +    for (let i = 1; i < calc; i++){
@shimizu0623 
ここは最後に0を詰める処理だと思いますが、calcの分だけ0を詰める必要がありますが、calc = 1の場合ここを通らないかと思います 🙇 

```
11 2
00101010111
```

だと、11が正解ですが、1になってしまうので、これが原因かもです 🙇

2022-10-01 03:45 UTC, shimizu0623 commented on rank_C/C111.js
> +    for (let i = 1; i < calc; i++){
たしかにこのままだと繰り返す範囲が間違っておりました！🙇💦
修正致します！

2022-10-01 03:46 UTC, shimizu0623 commented
コメントありがとうございます！
教えていただいた箇所を修正したところ、全問正解できました😊
お手すきの際にご確認よろしくお願い致します🙇🙇

2022-10-01 15:04 UTC, yuki-omoto approved these changes
@shimizu0623 
こちらも全問正解さすがです！！ 🙇

2022-10-01 15:04 UTC, merged