C113:一人でスゴロク
shimizu0623/paiza_practice pull request #89
Opened 2022-09-05 05:12 UTC by shimizu0623

お疲れ様です！
ダメ元で解いてみたのですが、やっぱり全問正解できませんでした！笑
そもそも解き方が違いますでしょうか？？🤔
お手数ですが、こちらもヒントいただけますと幸いです🙇🙇
よろしくお願いします！

![image](https://user-images.githubusercontent.com/89590207/188364920-4bac1126-947a-462d-a0ef-e8d996bf9e59.png)

2022-10-01 05:48 UTC, shimizu0623 commented on rank_C/C113.js
> +  let answer = 'still ' + dice;
最初から配列にしておくのは思いつきませんでした！👀💡
修正いたします！🙇

それから、答えの計算はどこが足りないのでしょうか？
マス目がxの時の処理を追加してみたのですが、結果が変わりませんでしたので再度質問させていただきました🙇🙇
恐れ入りますが、ご教授の程よろしくお願い致します🙇

2022-10-01 15:23 UTC, yuki-omoto requested changes
@shimizu0623 

ごめんなさい、、意味わからない回答してしまっていました 🙇 
こうじゃないかなというのを↓に作ってみました。。
修正箇所にコメント入れていますが、提出前には削除してください 🙇 

```
process.stdin.resume();
process.stdin.setEncoding('utf8');
var lines = [];
var reader = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});
reader.on('line', (line) => {
  lines.push(line);
});
reader.on('close', () => {
  const [grids, times] = lines[0].split(' ').map(n => parseInt(n));
  let dice = 0;
  let count = 0;
  let answer = 'still ' + dice;
  for (let i = times + 1; i < lines.length; i++){
    const value = parseInt(lines[i]);
    dice += value;
    count++;

    if (lines[dice] === 'r'){
        dice = 0;
    } else if (lines[dice] === '+'){
        dice += 1;
    } else if (lines[dice] === '-'){
        dice -= 1;
    }

    if (grids <= (dice + 1)){ // diceは0スタートなのに対し、gridsは1スタートなので合わせるため
        answer = 'goal ' + count;
        break;
    }
    answer = 'still ' + dice; // 終わらなかった場合、どこにいたかを出力する仕様を実現
  }

  console.log(answer.split(' ').join('\n'));
});
```

2022-10-01 15:25 UTC, yuki-omoto commented
念の為、僕はこれで正解でした！ 🙇 

```
process.stdin.resume();
process.stdin.setEncoding('utf8');
// 自分の得意な言語で
// Let's チャレンジ！！
var lines = [];
var reader = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});
reader.on('line', (line) => {
  lines.push(line);
});
reader.on('close', () => {
    const [n, m] = lines[0].split(' ').map(n => parseInt(n))
    const panels = ['x'].concat(lines.slice(1, n - 1)).concat(['x'])
    const dices = lines.slice(n - 1)
    let current = 0
    let endedAt = undefined
    for (let i = 0; i < dices.length; i++) {
        const step = parseInt(dices[i])
        current += step
        const effect = panels[current]
        switch (effect) {
            case '+':
                current++
                break
            case '-':
                current--
                break
            case 'r':
                current = 0
                break
            case 'x':
                break
        }
        
        if (current >= (panels.length - 1)) {
            endedAt = i + 1
            break
        }
    }
    console.log((endedAt ? ['goal', endedAt] : ['still', current]).join('\n'))
});
```

2022-10-02 03:21 UTC, shimizu0623 commented
コメントありがとうございます！
教えていただいたところを修正してみたところ、〇の数は増えたのですが、
全問正解はできませんでした😢ので、大本さんのコードを参考にさせていただきました🙇🙇
後程ご確認よろしくお願い致します🙇

2022-10-02 04:42 UTC, yuki-omoto approved these changes
@shimizu0623 
間違ってばかりでごめんなさい 🙇
修正確認しました！
人のコードを読む(理解する)のは勉強になると思いますので、わからないところがあったら聞いてくださいね 🙇

2022-10-02 04:42 UTC, merged