C005:アドレス調査
shimizu0623/paiza_practice pull request #90
Opened 2022-09-05 05:46 UTC by shimizu0623

お疲れ様です！
最後の１ケースがどうしても正解になりませんでした😢何が引っかかってしまっているのでしょう？🤔
お手数ですが、ヒントいただけますと幸いです🙇
よろしくお願いします！

![image](https://user-images.githubusercontent.com/89590207/188368899-223554b3-1c49-46d1-8f2c-5017592fb979.png)

2022-09-19 15:33 UTC, yuki-omoto requested changes
@shimizu0623 
これが原因かはわかりませんが、コメントさせていただきました 🙇 
これでも解決できなかったら申し訳ありません。。 🙇

2022-09-19 15:33 UTC, yuki-omoto commented on rank_C/C005.js
> +        if (4 === j){
@shimizu0623 
4が来たら、数字の区切りが5つ以上あるということでNGというロジックかと思いますが、区切りが2つや3つしかない場合はどうしましょう？ 🙇 

```
1
11.222.10
```

という入力を試すと、Trueと返ってきました 🙇

2022-10-01 06:07 UTC, shimizu0623 commented on rank_C/C005.js
> +        if (4 === j){
区切りが少ないパターンを考慮しておりませんでした🙇💦
修正いたします！🙇

2022-10-01 06:09 UTC, shimizu0623 commented
お疲れ様です！コメントありがとうございました！🙇🙇
修正したところ、全問正解できました😊
お手すきの際に、ご確認よろしくお願い致します🙇

2022-10-01 17:34 UTC, yuki-omoto approved these changes
修正完璧です！！🙇

2022-10-01 17:34 UTC, merged