C065:【ぱいじょ！コラボ問題】数字あてゲーム
shimizu0623/paiza_practice pull request #92
Opened 2022-09-05 08:03 UTC by shimizu0623

こちらも少し正解できましたが、全問正解はできませんでした😢
お手すきの際にご確認よろしくお願い致します🙇🙇

![image](https://user-images.githubusercontent.com/89590207/188398904-067b4969-de88-41ed-b502-0ffc3f59a4e5.png)

2022-09-20 12:52 UTC, yuki-omoto requested changes
@shimizu0623 
ロジックは正しそうです！
<と>は区別して処理しないといけないかと思いますので、そこだけコメントさせていただきました 🙇

2022-09-29 15:00 UTC, shimizu0623 commented
お疲れ様です！
修正したところ、ほとんど正解になったのですが、２ケースのみ不正解に
なってしまいました😢ので、再度上げさせていただきました🙇
申し訳ございませんが、ヒントいただけますと幸いです🙇
ご確認よろしくお願い致します🙇🙇

2022-09-30 16:51 UTC, yuki-omoto requested changes
@shimizu0623 

問題の条件的に、↓のような入力もあり得るのですが、これで実行してみるとエラーになりました 🙇 
正解は 100 と表示されることなのですが、これが対応できたら、全問正解になるかもです 🙇 

```
1
/ 100
```

ヒントわかりにくかったらおっしゃってくださいね 🙇

2022-10-01 16:34 UTC, yuki-omoto commented
@shimizu0623 

取り急ぎ僕はこれで全部正解でした 🙇 

```
process.stdin.resume();
process.stdin.setEncoding('utf8');
// 自分の得意な言語で
// Let's チャレンジ！！
var lines = [];
var reader = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});
reader.on('line', (line) => {
  lines.push(line);
});
reader.on('close', () => {
    let range = [0, 101]
    let answer = undefined
    const rules = lines.slice(1).map(line => line.split(' '))
    
    const lts = rules.filter(rule => rule[0] === '<').map(rule => rule[1])
    if (lts.length > 0) {
      range[1] = Math.min(...lts)
    }
    const gts = rules.filter(rule => rule[0] === '>').map(rule => rule[1])
    if (gts.length > 0) {
      range[0] = Math.max(...gts)
    }
    const multiples = rules.filter(rule => rule[0] === '/').map(rule => rule[1]) //.reduce((acc, cur) => acc * cur[1], 1)
    
    const [start, left] = range
    for (let i = (start + 1); i < left; i++) {
        if (multiples.every(multiple => i % multiple === 0)) {
            answer = i
            break
        }
    }
    console.log(answer);
});
```

2022-10-01 16:41 UTC, yuki-omoto commented
@shimizu0623 
清水さんのコードだとこれでいけるような気がします 🙇 
間違っていたら申し訳ありません。。

```
process.stdin.resume();
process.stdin.setEncoding('utf8');
var lines = [];
var reader = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});
reader.on('line', (line) => {
  lines.push(line);
});
reader.on('close', () => {
  const list = [];
  const hintMin = [];
  const hintMax = [];
  let answer = 0;

  for (let i = 1; i < lines.length; i++){
    let [sign, hintNumber] = lines[i].split(' ');
    hintNumber = parseInt(hintNumber);

    if (sign === '<'){
      hintMax.push(hintNumber);
    } else if (sign === '>'){
      hintMin.push(hintNumber);
    } else if (sign === '/'){
      list.push(hintNumber);
    }
  }

  // >や<がない時のminとmaxを決めておく
  let min = 0
  let max = 101
  if (hintMin.length > 0) {
    min = Math.max(...hintMin);
  }
  if (hintMax.length > 0) {
    max = Math.min(...hintMax);
  }
  let isCheck = true;

  for (let i = min + 1; i < max; i++){
    for (let j = 0; j < list.length; j++){
      if (i % list[j] !== 0){
        isCheck = false;
        break;
      }
    }

    if (isCheck){
      answer = i;
      console.log(answer);
      return;
    }

    isCheck = true;
  }
});
```

2022-10-02 02:24 UTC, shimizu0623 commented
コメントありがとうございます！！
minとmaxを決めておくコードを追記したところ、全問正解できました！🙇
修正完了いたしましたので、後程ご確認よろしくお願い致します🙇

2022-10-02 04:46 UTC, yuki-omoto approved these changes
完璧です！！

2022-10-02 04:46 UTC, merged