C069:お祭りの日付
shimizu0623/paiza_practice pull request #95
Opened 2022-09-09 11:21 UTC by shimizu0623

お疲れ様です！
半分正解まで辿り着いたのですが、ギブアップだったので上げさせていただきます🙇
他の良いやり方やヒントいただけますと幸いです🙇💦
ご確認よろしくお願い致します🙇🙇

![image](https://user-images.githubusercontent.com/89590207/189338692-4bc6924c-147d-4ebd-b849-e62aae154435.png)

2022-09-20 12:20 UTC, yuki-omoto requested changes
@shimizu0623 
この問題すごく難しいですね。。 🙇 
清水さんの回答見たのですが、合っていそうに見えて、どこが間違っているのかわかりませんでした 🙇 

こういうややこしい問題は計算によって答えを出すよりも、単純にシミュレーションした方が楽かもです 🙇 

僕も最初計算でやろうとしたのですが、複雑すぎてやめました 🙇 
その代わりはwhileループで当日から+1を繰り返して、祭りの日になったら終わるというやり方で正解できたので、そちらを試していただくのはいかがでしょうか？ 🙇 
申し訳ありません 🙇

2022-10-01 16:04 UTC, yuki-omoto commented
@shimizu0623 

僕はこれで一応全部正解でした 🙇 
あんまり効率良くないですが、whileループで毎日数えていった感じです 🙇 

```
process.stdin.resume();
process.stdin.setEncoding('utf8');
// 自分の得意な言語で
// Let's チャレンジ！！
var lines = [];
var reader = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});
reader.on('line', (line) => {
  lines.push(line);
});
reader.on('close', () => {
    const [year, month, day] = lines[0].split(' ').map(n => parseInt(n))
    const [targetMonth, targetDay] = lines[1].split(' ').map(n => parseInt(n))

    let currentYear = year
    let currentMonth = month
    let currentDay = day
    let daysPassed = 0
    while (currentYear % 4 !== 1 || currentMonth !== targetMonth || currentDay !== targetDay) {
        
        const monthIsOdd = currentMonth % 2 === 1
        if (monthIsOdd && currentDay === 13) {
            currentMonth++
            currentDay = 1            
        } else if (!monthIsOdd && currentDay === 15) {
            currentMonth++
            currentDay = 1
        } else {
            currentDay++
        }
        
        if (currentMonth > 13) {
            currentYear++
            currentMonth = 1
            currentDay = 1
        }
        daysPassed++
    }
    
    console.log(daysPassed);
});
```

2022-10-02 03:02 UTC, shimizu0623 commented
コメントありがとうございます！！
大本さんのコードを参考に修正させていただきました！🙇
後程ご確認よろしくお願い致します🙇

2022-10-02 04:47 UTC, yuki-omoto approved these changes
修正確認しました！ 🙇

2022-10-02 04:47 UTC, merged